### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by Mugge66** [dkjonas/Wavin-AHC-9000-mqtt#10]
Hey And sry for asking. Im trying to get this to work but it keeps saying socket error disconnecting.

Im thinking it could be related to user/password. 

Im running my mqtt in docker on synology and im not using user or password. 

in the private.sh config file in your script what should the user and password text be. do i just delete you text and leave it like    ""   // username   <-- like this ?

**Comment by dkjonas** [comment]
Try setting the username/password to "" or to String(NULL) (no quotes).

If that it not working remove "MQTT_USER.c_str(), MQTT_PASS.c_str()," from line 239 in main.cpp.

**Comment by Mugge66** [comment]
"" Works. :-)   Nice Job. :-)
