### ISSUE TITLE
Question regarding the hardware setup

### ISSUE THREAD

**Issue by maisun** [dkjonas/Wavin-AHC-9000-mqtt#13]
Hi Jonas,

Thank you for sharing the project, it is great to allow home automation systems to control central heating system through MQTT.
I'd very much like to give a try but not sure how to start, I have no experience with the hardware you mentioned and how to connet them. Would it be possible to share some tutorial on how to assemble the device and/or are you interested in selling the device?
Thank you in advance!

**Comment by dkjonas** [comment]
Hi, 

The parts and connections are listed here: https://github.com/dkjonas/Wavin-AHC-9000-mqtt
It is not that hard to connect, but if you don't have experience doing it, it can understand it may be difficult to follow those instructions.

I think the best I can do is to try to verify your connections before you connect the circuit to the AHC. Like in this issue: https://github.com/dkjonas/Wavin-AHC-9000-mqtt/issues/7 (look at the bottom for pictures)
