### ISSUE TITLE
Maybe not a issue, Decimal on set temperature

### ISSUE THREAD

**Issue by Allan3dk** [dkjonas/Wavin-AHC-9000-mqtt#17]
On my room sensors I can set the temperature by half degrees, but in the integration I can only set it in full temperatures, have I done something wrong or is it just not possible?

**Comment by hsk-dk** [comment]
i have the same issue, in home assistant "target_temp_step" is set to 1.
This can be changed manually, but it would be nice if the default step could be set to 0.5..
