### ISSUE TITLE
Not an issue but more a feature request

### ISSUE THREAD

**Issue by jascdk** [dkjonas/Wavin-AHC-9000-mqtt#2]
Hi.

Would it be possible to add / define som pins in the code for to use as led indicators? More if a box for the print is made, it would be nice to have some LED´s which shows - MQTT connected (and MQTT activity) and maybe a LED for WIFI connected?

**Comment by dkjonas** [comment]
Wifi and MQTT connected are easy to do.
MQTT activity is a bit more complicated as communication is fast, so just turning on a led on during communication will not be visible. It will have to be on for maybe 200ms to be visible, so some extra delay has to be added.

**Comment by jascdk** [comment]
Cool - could you update the code / possibility for that? I am thinking about making a case for the module (with the esp) so it would be handy to see what is going on:)

**Comment by jascdk** [comment]
> Wifi and MQTT connected are easy to do.
> MQTT activity is a bit more complicated as communication is fast, so just turning on a led on during communication will not be visible. It will have to be on for maybe 200ms to be visible, so some extra delay has to be added.

Hi again:) Would it be possible to add for example 2 pins, which is assigned for showing the wifi connected status and perhaps also a power on status - and maybe also the MQTT status if possible with some delay on:)

It would be nice to visualize when putting everything into a 3d printed case:)

**Comment by jascdk** [comment]
> Wifi and MQTT connected are easy to do.
> MQTT activity is a bit more complicated as communication is fast, so just turning on a led on during communication will not be visible. It will have to be on for maybe 200ms to be visible, so some extra delay has to be added.

Hi Again:) Would this be possible to adopt to the code?

**Comment by dkjonas** [comment]
It is possible, yes. But I am busy with other projects at the moment and I don't see this as a high priority task, as the esp should always be on and connected once it has been set up correctly. Also, I can't test this on my current hardware, as I use all pins on the esp for other purposes.
