### ISSUE TITLE
One thermostat to two channels - how to

### ISSUE THREAD

**Issue by Christoffer-da** [dkjonas/Wavin-AHC-9000-mqtt#22]
Hi 
I have a house with 6 rooms, with 7 channels/zones, meaning that one Thermostat is controlling two channels/zones.
 
Everything works great, but this bigger room shows as two seperate climate entities, is it possible to combine theese in a way. Temp reading is always identical, but right now it is possible to set seperate target temperatures, but everything should always be identical for theese two.

Also, i think that hooking up the NodeMCU two the Wavin controller, and playing with target temperatures have messed up the Thermostat binding, so it only controls target temperature for one of the zones now, and not both. Current temp reading is showing on both entities, but only one is changing target temp, when i adjust manually on the thermostat.

Hope my explanation makes sense.

**Comment by dkjonas** [comment]
Sorry for the late reply. I don't think this project can change thermostat bindings, as it mostly reads from the AHC. Only thing written is the target temperature, standby temperature, and operating mode.

I have a setup like yours with one thermostat for two zones. I have just hidden the entry not used in HomeAssistant.
