### ISSUE TITLE
Compatible with Wavin Sentio?

### ISSUE THREAD

**Issue by kernest** [dkjonas/Wavin-AHC-9000-mqtt#25]
Hi,

Have this been testing with the Wavin Sentio system?

Not sure how to check if it is compatible, but Sentio also have modbus interface.

Looking forward to hear from you!

**Comment by dkjonas** [comment]
Had a quick look, and even though it is using modbus, the register usage is different. So it is not compatible with this project.

**Comment by kernest** [comment]
Thanks for looking at it! Highly appreciated!
