### ISSUE TITLE
Possible to use the Display together with the MQTT interface?

### ISSUE THREAD

**Issue by jascdk** [dkjonas/Wavin-AHC-9000-mqtt#3]
Hi. Is it possible to use both Display and MQTT interface at the same time since there is 2 x Ethernet slots on the AHC 9000 unit?

**Comment by dkjonas** [comment]
Hi. I'm not quite sure about this. I think I read somewhere, that it is not possible.
Looking at the PCB for the AHC unit, I can see, that both connectors are connected in parallel. So, if the display sends a message to the AHC at the same time as the MQTT interface, the messages will collide. I don't remember anything in documentation on how to avoid this. 

The reason the AHC has two connectors, it to be able to connect two AHC's together and control them by one display. I think this is rather unusual setup, so my code doesn't handle this case; It can only control one AHC.

**Comment by jascdk** [comment]
Thanks for the answer:)
