### ISSUE TITLE
How to find other units information

### ISSUE THREAD

**Issue by andreapier** [dkjonas/Wavin-AHC-9000-mqtt#37]
Hi, this is not an issue but I need help nonetheless.
I own a mechanical ventilation system by wavin. A RDCD 3.0 SH to be precise.
It has an RJ45 but it's not the classica LAN port. The device actually turns off if I plug a normal ethernet cable.
I suspect it the same connector described here, and I'd like to know more about it.
Do you have any guidance on how/where I can get more info?
I don't have a manual or a referente to the technician who installed it. Wavin is totally useless too, I tried to contact them but it was a dead end.
Thanks for your time and your effort on this peoject!!

**Comment by jascdk** [comment]
Hi :) I have a suggestion for you. This project here has evolved quite a lot since a lot of people these days use Home Assistant managing their smarthomes. Therefore you might take a look at this repo here https://github.com/heinekmadsen/esphome_components/tree/main which has code for controlling a Wavin AHC9000 floor heat controller. Im using a esp32 device controlling modbus on the ahc unit - and also the same module for controlling our HVAC system from Nilan.

If you want, I can help you get in contact with this guy who has this repo here - maybe he has some modules left. https://github.com/nic6911/ESP32_Modbus_Module

I think your system may use modbus for communication, but if I were you, I would contact wavin here in Denmark and ash for the modus-protocol on the system you have. Then we can se if we can figure out communicating with it;)

All the best

Jacob / Denmark

**Comment by stefboerrigterWavin** [comment]
@andreapier 
I found these registers:
![image](https://github.com/dkjonas/Wavin-AHC-9000-mqtt/assets/86054364/016e2d4b-b4d4-4cd6-99da-c38af2e48a58)

**Comment by andreapier** [comment]
@jascdk thanks, I will try to contact them

> @andreapier I found these registers: ![image](https://private-user-images.githubusercontent.com/86054364/318675364-016e2d4b-b4d4-4cd6-99da-c38af2e48a58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwODY1MzUsIm5iZiI6MTcxMjA4NjIzNSwicGF0aCI6Ii84NjA1NDM2NC8zMTg2NzUzNjQtMDE2ZTJkNGItYjRkNC00Y2Q2LTk5ZGEtYzM4YWYyZTQ4YTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE5MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZDgzZTBkM2YyOWIyN2NjZmE0YTkyYTkxYmRhNzc3NTBhYzI5YjJmZjlmMTYxYTJhMjI5ODQ1YWQyN2RjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DK3tUykm_UpjSCTTvnksTW4mlFEtPbXpV2ywZs0jGLw)

Mind sharing your source?
Btw, THANKS!!! This looks like exactly what I was looking for!

**Comment by stefboerrigterWavin** [comment]
I don't believe the sources are re-usable for this project or a relevant project. It's tailored for our products. 
Next to that, we don't have a policy to open our source-code of existing products.

**Comment by andreapier** [comment]
> I don't believe the sources are re-usable for this project or a relevant project. It's tailored for our products. Next to that, we don't have a policy to open our source-code of existing products.

@stefboerrigterWavin 
Sorry, yesterday I was on mobile and did not immediately notice your username... I guess you are a wavin employee.
First, let me say thank you again. Second, I did not mean to share the source code. I meant if you could share the source where you got those registers, like an installer manual or anything like that (probably the word "source" was a little misleading). But I guess it is internal documentation, and it is just fine if company policies disallow to share it.  
  
On another note, would you (and can you) also share relevant information about the RJ45 port and the protocol used?

**Comment by andreapier** [comment]
> I don't believe the sources are re-usable for this project or a relevant project. It's tailored for our products. Next to that, we don't have a policy to open our source-code of existing products.

@stefboerrigterWavin Sorry to annoy you, but I was wondering if you could at least confirm that the schematic of the RJ45 port in RDCD 3.0 SH is the same as the AHC-9000 or not. Thanks!

**Comment by stefboerrigterWavin** [comment]
No Problem, 
Yes, the information is obtained from internal documents. 
The RJ45 port on the Ventilation unit is suitable for modbus communication (protocol see image i shared before).
Wiring is(should be) identical to other Wavin products for Modbus:
![image](https://github.com/dkjonas/Wavin-AHC-9000-mqtt/assets/86054364/6699733b-aebb-4229-9a2e-11ff6310b7e1)

Which matches schematics from this repo documentatation

**Comment by dkjonas** [comment]
I don't think the device shares the software protocol of this project, so I will suggest creating a different repo for the device, where you can share the details.

**Comment by andreapier** [comment]
> I don't think the device shares the software protocol of this project, so I will suggest creating a different repo for the device, where you can share the details.

Done, [here is the repo](https://github.com/andreapier/esp-rdcd) for people who could be interested.
